/** CONSTANTS DEFINITION */

var TOWER_NB_LAYERS = 6;
var GAME_SPACING = 10;
var TOP_SPACING = 50;
var TOWER_SPACING = 10;
var POLE_WIDTH = 10;
var BASE_HEIGHT = 5;
var LAYER_HEIGHT = 25;
var LAYER_SPACING = 5;
var LAYER_MIN_WIDTH = 20;
var LAYER_ANIMATION_SPACING = 20;
var ANIMATION_SPEED = 6;
